### ISSUE TITLE
Large pdf files cannot be sent

### ISSUE THREAD

**Issue by GGSIPUResultTracker** [ggsipu-usict/ggsipu-notice-tracker#1]
`12/01/2019 04:23:49 AM [ERROR]: Failed to send [ordpayfix230818.pdf]. Recieved 413 http code from /sendDocument.`
`12/01/2019 04:23:49 AM [ERROR]: FAILED to SENT {'date': '23-08-2018', 'title': 'Statement of revised fixation of pay consequent upon implementation of order dated 10.08.2018 of University withdrawing the benefits of Order No. 58 & 57 of Service Department of GNCTD (93 Employees)', 'url': '/pubinfo/ordpayfix230818.pdf'}.`

**Few notices have pdf > 50mb** which lead to HTTP 413 as Telegram BOTs cannot sent more than 50mb from inputstreams.

**Comment by ashutoshvarma** [comment]
already fix that in e78f51a48b190396e275743d67ab61e096892e2a.
Please check commit history before reporting a issue :unamused:.
