### ISSUE TITLE
Cannot send some notices. 400 Bad Request

### ISSUE THREAD

**Issue by GGSIPUResultTracker** [ggsipu-usict/ggsipu-notice-tracker#2]
Some notices cannot be sent because of 400 Bad Request.
Here are logs from my server:-
`12/01/2019 05:27:12 AM [ERROR]: Failed to send [ntprg130819.pdf]. Recieved 400 http code from /sendDocument. `
`12/01/2019 05:27:12 AM [ERROR]: FAILED to SENT {'date': '13-08-2019', 'title': 'Orientation_programme for B.Tech/M.Tech/MCA (SE) of newly admitted students during the academic session 2019-20,USICT', 'url': '/Pubinfo2019/ntprg130819.pdf'}. `

**Comment by ashutoshvarma** [comment]
Looks like escaping problem. Markdown special characters are not being escaped.
`Orientation_programme for` here `_` is causing probem.

**Comment by ashutoshvarma** [comment]
added escaping for  `*`, `_`,  `` ` ``  in 47c0bc85f138689cc4fb6a5da7dcbc87339d4003
