### ISSUE TITLE
Broken links in telegram notice updates

### ISSUE THREAD

**Issue by GGSIPUResultTracker** [ggsipu-usict/ggsipu-notice-tracker#3]
Notice links in telegram messages are broken

![image](https://user-images.githubusercontent.com/52526972/71560163-3b7c2080-2a8c-11ea-950b-1df541b411dc.png)

![image](https://user-images.githubusercontent.com/52526972/71560174-5a7ab280-2a8c-11ea-8be4-750f03edaafd.png)

All the links with whitespaces are not parsed properly in telegram markdown

**Comment by ashutoshvarma** [comment]
sorry for late reply, my laptop died. 
Clearly its a url encoding problem. Markdown doesn't like spaces in links, we can encode urls to fix this.
